---
- name: Configure Jenkins and Install Plugins
  hosts: jenkins
  become: yes
  tasks:
    - name: Install required Jenkins plugins
      community.general.jenkins_plugin:
        name: "{{ item }}"
        state: present
        url: "http://localhost:8080"
        url_username: admin
        url_password: "{{ jenkins_admin_password }}"
      loop:
        - git
        - pipeline-aws
        - blueocean
        - sonarqube-scanner
        - docker-plugin
        - kubernetes
      register: plugin_install

    - name: Ensure Jenkins service is restarted after plugin installation
      ansible.builtin.systemd:
        name: jenkins
        state: restarted
      when: plugin_install.changed
